import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import { Reduxprovider } from "@/provider/redux-provider";

const inter = Rubik({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Reduxprovider>
          <Header />
          <main className="bg-[#F5F6F9]">{children}</main>
          <Footer />
        </Reduxprovider>
      </body>
    </html>
  );
}
